debug: true
providers:
    docker:
        network: traefik-local-network
        exposedByDefault: false
    file:
        filename: dynamic.yml

entryPoints:
    http:
        address: ":80"

    https:
        address: ":443"

certificatesResolvers:
    le:
        acme:
            # Uncomment the line to use Let's Encrypt's staging server, leave commented to go to prod.
            # caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
            # Use a TLS-ALPN-01 ACME challenge. Optional (but recommended)
            # tlsChallenge: true
            # Use a DNS-01 ACME challenge rather than HTTP-01 challenge. mandatory for wildcard certificate generation.
            # dnsChallenge: true
            email: your@example.com
            storage: acme.json
            httpChallenge:
                # used during the challenge
                entryPoint: http

#api:
#    insecure: true
#    dashboard: true
#    debug: true

accessLog:
    filePath: /host/logs/access.log
    format: json
